ForumPrototype5/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic.base import RedirectView
from django.contrib.auth import views as authViews
from web_app.views import login as custom_login

## for media files
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$',RedirectView.as_view(pattern_name='loginPageURL'),name='loginShortURL'),
    url(r'accounts/login/$',custom_login,{'template_name': 'registration/login-signup.html'},name='loginPageURL'),
    url(r'accounts/logout/$',authViews.logout,name='logoutPageURL',kwargs={'next_page':'/'}),
    url(r'',include('web_app.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web_app/urls.py
from django.conf.urls import url
from web_app.views import (IndexPage,registerNewUser,CreateQueryPage,ShowQueryPage,ShowQueryListByCategory,
                            ShowSearchResult,CreateDiscussionThreadsQueryPage,CreateDiscussionThreadsSolutionPage,
                            CreateAnswerPage,exportCSVtrainData,populate_train_db,UpdateUpvote,UpdateDownvote)

app_name = 'web_app'


urlpatterns = [
url(r'^$',IndexPage.as_view(),name='IndexPageURL'),
url(r'^register/$',registerNewUser,name='RegisterNewuUserURL'),
url(r'^ask/$',CreateQueryPage.as_view(),name='CreateQueryPageURL'),
url(r'^query/(?P<pk>\d+)#(?P<elementid>[a-zA-Z\d]+)$',ShowQueryPage.as_view(),name='ShowQueryPageWithElementIDURL'),
url(r'^query/(?P<pk>\d+)/$',ShowQueryPage.as_view(),name='ShowQueryPageURL'),
url(r'^query/(?P<pk>\d+)/upvote-update-answer/(?P<answerpk>\d+)$',UpdateUpvote.as_view(),name='UpdateUpvoteURL'),
url(r'^query/(?P<pk>\d+)/downvote-update-answer/(?P<answerpk>\d+)$',UpdateDownvote.as_view(),name='UpdateDownvoteURL'),
url(r'^queries/(?P<category>[\w-]+)/$',ShowQueryListByCategory.as_view(),name='ShowQueryListByCategoryURL'),
url(r'^search/$',ShowSearchResult.as_view(),name='InitiateSearchURL'),
url(r'^search/?(?P<search_query>[\w-]+)/$',ShowSearchResult.as_view(),name='ShowSearchResultURL'),
url(r'^create-query-comment/(?P<querypk>\d+)/$',CreateDiscussionThreadsQueryPage.as_view(),name='CreateDiscussionThreadsQueryPageURL'),
url(r'^create-answer-comment/(?P<answerpk>\d+)/(?P<querypk>\d+)$',CreateDiscussionThreadsSolutionPage.as_view(),name='CreateDiscussionThreadsSolutionPageURL'),
url(r'^create-answer/(?P<querypk>\d+)/$',CreateAnswerPage.as_view(),name='CreateAnswerPageURL'),
url(r'^export_training_data/$',exportCSVtrainData,name='ExportCSVTrainDataURL'),
url(r'^populate_training_data/$',populate_train_db,name='PopulateTrainDBURL'),
]

web_app/models.py
from django.db import models

# Create your models here.

web_app/forms.py
from django import forms
from app_models import models
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User



class UserInfoRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username','first_name','last_name','email','password1','password2')
class UserProfileInfoRegistrationForm(forms.ModelForm):
    class Meta:
        model = models.UserProfileModel
        fields = ('profile_image',)

class CreateQueryForm(forms.ModelForm):

    class Meta:
        model = models.QueriesModel
        # exclude = ('text',)
        exclude = ('created_by','created_date','last_modified','is_spam','tag1','tag2','tag3','tag4','tag5','answer_summary')

        widgets = {
        'title':forms.TextInput(attrs={'label':'Your Query'}),
        }

class CreateTagsForm(forms.ModelForm):
    class Meta:
        model = models.TagsModel
        fields = '__all__'
class CreateAnswersForm(forms.ModelForm):
    class Meta:
        model = models.AnswersModel
        fields = ('text',)
class CreateDiscussionThreadsSolutionForm(forms.ModelForm):
    class Meta:
        model = models.DiscussionThreadsSolutionModel
        fields =('text',)


        widgets = {
        'text' : forms.TextInput(attrs={'class':'textinputclass','placeholder':'enter comment to discuss on solution'})
        }

class CreateDiscussionThreadsQueryForm(forms.ModelForm):
    class Meta:
        model = models.DiscussionThreadsQueryModel
        fields = ('text',)

        widgets = {
        'text' : forms.TextInput(attrs={'class':'textinputclass','placeholder':'enter comment to discuss question'})
        }

class CreateServiceForm(forms.ModelForm):
    class Meta:
        model = models.ServicesModel
        fields = '__all__'


## other Functionality forms
class SearchBarForm(forms.Form):
    search_query = forms.CharField(label='Search',widget=forms.TextInput(attrs={'class':'search_bar_class','placeholder':'search the forum'}))

web_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import TemplateView,CreateView,DetailView,ListView,DeleteView,UpdateView
from web_app.forms import UserInfoRegistrationForm,UserProfileInfoRegistrationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from web_app import forms as web_app_forms
from app_models import models as forumModels
from django.urls import reverse,reverse_lazy
from django.shortcuts import get_object_or_404
from django.contrib.postgres.search import SearchVector,SearchRank,SearchQuery
from django.contrib.auth.views import login as auth_views_login
from django.contrib.auth.forms import AuthenticationForm

from web_app.train import export_to_csv,save_train_data
# Create your views here.

##Landing Page
class IndexPage(ListView):
    model = forumModels.QueriesModel
    template_name = 'web_app/index-new2.html'
    context_object_name = 'query_list'
    paginate_by = 2
    queryset = forumModels.QueriesModel.objects.all().order_by('-created_date')

    def get_context_data(self,**kwargs):
        context = super(IndexPage,self).get_context_data(**kwargs)
        context['tags_list'] = forumModels.TagsModel.objects.all()
        context['search_bar_form'] = web_app_forms.SearchBarForm()
        context['category_list'] = forumModels.ServicesModel.objects.all()
        return context

#login_view using django auth
def login(*args, **kwargs):
    registration_form1 = web_app_forms.UserInfoRegistrationForm()
    registration_form2 = web_app_forms.UserProfileInfoRegistrationForm()

    extra_context = {'reg_form1': registration_form1, 'reg_form2': registration_form2}
    return auth_views_login(*args, extra_context=extra_context, **kwargs)

## Signing up a new user
def registerNewUser(request):
    registered = False
    errors = False
    err1 = None
    err2 = None


    if request.method == 'POST':
        user_form = UserInfoRegistrationForm(data = request.POST)
        profile_form = UserProfileInfoRegistrationForm(data = request.POST)
        print(str(request.POST))
        if user_form.is_valid() and profile_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.password = request.POST.get('password1')
            print(str(new_user))
            print("password before - "+str(new_user.password))
            # for (key,arg) in new_user:
            #     print(" key - {} arg - {}".format(key,arg))
            new_user.set_password(new_user.password)
            print("password after - "+str(new_user.password))
            new_user.save()
            profile = profile_form.save(commit=False)
            profile.user = new_user

            if 'profile_image' in request.FILES:
                profile.profile_image = req.FILES['profile_image']
            profile.save()

            registered = True
        else:
            err1 = profile_form.errors
            err2 = user_form.errors
            print(err1)
            print(err2)
            errors = True
    else:
        user_form = UserInfoRegistrationForm()
        profile_form = UserProfileInfoRegistrationForm()
    login_form = AuthenticationForm()

    return render(request,'registration/registration.html',{'registered':registered,'errors':errors,'reg_form1':user_form,'reg_form2':profile_form,'error_list1':err1,'error_list2':err2,'login_form':login_form})

#Creating a new Query Post
class CreateQueryPage(LoginRequiredMixin,CreateView):
    login_url = reverse_lazy('loginPageURL')
    form_class = web_app_forms.CreateQueryForm
    template_name = 'web_app/create_query2.html'
    model = forumModels.QueriesModel

    def form_valid(self,form):
        list_of_tags = form.instance.tags
        list_of_tags_trimmed = list_of_tags.split(",")[:5]
        print(list_of_tags_trimmed)
        list_of_tags_trimmed = [tag.strip() for tag in list_of_tags_trimmed]
        print(list_of_tags)
        print(list_of_tags_trimmed)
        if len(list_of_tags_trimmed) >= 1:
            if list_of_tags_trimmed[0] != '':
                form.instance.tag1 = forumModels.TagsModel.objects.get_or_create(tagName = list_of_tags_trimmed[0])[0]
        if len(list_of_tags_trimmed) >= 2:
            if list_of_tags_trimmed[1] != '':
                form.instance.tag1 = forumModels.TagsModel.objects.get_or_create(tagName = list_of_tags_trimmed[1])[0]
        if len(list_of_tags_trimmed) >= 3:
            if list_of_tags_trimmed[2] != '':
                form.instance.tag1 = forumModels.TagsModel.objects.get_or_create(tagName = list_of_tags_trimmed[2])[0]
        if len(list_of_tags_trimmed) >= 4:
            if list_of_tags_trimmed[3] != '':
                form.instance.tag1 = forumModels.TagsModel.objects.get_or_create(tagName = list_of_tags_trimmed[3])[0]
        if len(list_of_tags_trimmed) >= 5:
            if list_of_tags_trimmed[4] != '':
                form.instance.tag1 = forumModels.TagsModel.objects.get_or_create(tagName = list_of_tags_trimmed[4])[0]
        form.instance.created_by = self.request.user.profile
        return super(CreateQueryPage,self).form_valid(form)

    def get_context_data(self,**kwargs):
        context = super(CreateQueryPage,self).get_context_data(**kwargs)
        context['tags_list'] = forumModels.TagsModel.objects.all()
        context['search_bar_form'] = web_app_forms.SearchBarForm()
        context['category_list'] = forumModels.ServicesModel.objects.all()
        return context

    #success_url = reverse_lazy('web_app:ShowQueryPageURL',kwargs={'pk':pk_url_kwarg})

#DetailView of query
class ShowQueryPage(DetailView):
    template_name = 'web_app/query-new2.html'
    model = forumModels.QueriesModel
    context_object_name = 'query'

    def get_context_data(self, **kwargs):
        context = super(ShowQueryPage, self).get_context_data(**kwargs)
        context['query_discussion_form'] = web_app_forms.CreateDiscussionThreadsQueryForm()
        context['solution_discussion_form'] = web_app_forms.CreateDiscussionThreadsSolutionForm()
        context['category_list'] = forumModels.ServicesModel.objects.all()
        return context

class ShowQueryListByCategory(ListView):
    template_name = 'web_app/index-new2.html'

    model = forumModels.QueriesModel
    context_object_name = 'query_list'

    #
    def get_queryset(self):
        q_for_service = forumModels.ServicesModel.objects.filter(title__icontains=self.kwargs['category'].replace('-',' '))
        service = get_object_or_404(q_for_service)
        return forumModels.QueriesModel.objects.filter(service_area=service)
    def get_context_data(self,**kwargs):
        context = super(ShowQueryListByCategory,self).get_context_data(**kwargs)
        context['tags_list'] = forumModels.TagsModel.objects.all()
        context['search_bar_form'] = web_app_forms.SearchBarForm()
        context['category_list'] = forumModels.ServicesModel.objects.all()
        return context

class ShowSearchResult(ListView):
    template_name = 'web_app/index-new2.html'
    model = forumModels.QueriesModel
    context_object_name = 'query_list'

    def get_queryset(self):
        # + SearchVector('text') + SearchVector('service_area__title')
        search_vector = SearchVector('title')+ SearchVector('text') + SearchVector('service_area__title') + SearchVector('tags')
        search_query = SearchQuery(self.request.GET['search_query'])
        print(self.request.GET['search_query'])
        queryset = forumModels.QueriesModel.objects.annotate(rank=SearchRank(search_vector,search_query),search=search_vector).filter(search=self.request.GET['search_query']).order_by('-rank')
        return queryset
    def get_context_data(self,**kwargs):
        context = super(ShowSearchResult,self).get_context_data(**kwargs)
        context['tags_list'] = forumModels.TagsModel.objects.all()
        context['search_bar_form'] = web_app_forms.SearchBarForm()
        context['category_list'] = forumModels.ServicesModel.objects.all()
        context['list_title'] = "Search Results -"
        return context

class UpdateQueryPage(LoginRequiredMixin,UpdateView):
    model = forumModels.QueriesModel
    fields = ['text','title','tags','last_modified']
    template_name = 'web_app/create_query2.html'

class UpdateAnswerPage(LoginRequiredMixin,UpdateView):
    model = forumModels.AnswersModel
    fields = ['text']
    template_name = 'web_app/create_query2.html'

class CreateAnswerPage(LoginRequiredMixin,CreateView):
    model = forumModels.AnswersModel
    form_class = web_app_forms.CreateAnswersForm
    template_name = 'web_app/create_answer2.html'

    def get_context_data(self,**kwargs):
        context = super(CreateAnswerPage,self).get_context_data(**kwargs)
        context['query'] = forumModels.QueriesModel.objects.get(pk=self.kwargs['querypk'])
        context['category_list'] = forumModels.ServicesModel.objects.all()
        return context

    def form_valid(self,form):
        form.instance.created_by = self.request.user.profile
        form.instance.query = forumModels.QueriesModel.objects.get(pk=self.kwargs['querypk'])
        return super(CreateAnswerPage,self).form_valid(form)


class CreateDiscussionThreadsQueryPage(LoginRequiredMixin,CreateView):
    model = forumModels.DiscussionThreadsQueryModel
    form_class = web_app_forms.CreateDiscussionThreadsQueryForm
    template_name = 'web_app/query-new2.html'


    def form_valid(self, form):
        form.instance.created_by = self.request.user.profile
        form.instance.query = forumModels.QueriesModel.objects.get(pk=self.kwargs['querypk'])
        return super(CreateDiscussionThreadsQueryPage, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(ShowQueryPage, self).get_context_data(**kwargs)
        context['query_discussion_form'] = web_app_forms.CreateDiscussionThreadsQueryForm()

web_app/templates/web_app/create_query2.html
{% extends 'web_app/base2.html' %}

{% load staticfiles %}

{% block main_container %}
<div class="container">

<!--Form without header-->
<form method="POST">

<div class="card">
    <div class="card-block">

        <!--Header-->
        <div class="text-center">
            <h3> New Query</h3>
            <hr class="mt-2 mb-2">
        </div>

        <!--Body-->
        <div class="">
          {% csrf_token %}
          {{form.media}}
          {{ form.as_p }}

        </div>

    </div>

    <!--Footer-->
    <div class="modal-footer">
        <div class="options">
          <button type="submit"class="btn btn-info waves-effect">Post Your Query</button>
        </div>
    </div>

</div>

</form>

</div>

<!--/Form without header-->
{% endblock %}

web_app/templates/web_app/index-new2.html
{% extends 'web_app/base2.html' %}
<!-- jumbotron banner -->
{% load staticfiles %}
{% block main_container %}

<!-- jumbotron banner -->

<div class="row wow fadeIn" data-wow-delay="0.2s">
  <div class="col-md-12">
    <div class="jumbotron">
      <h2 class="h2-responsive">Forum for DRyiCE Clients</h2>
      <br>
      <form class="" action="{% url 'web_app:InitiateSearchURL' %}" method="GET" class="md-form">

        <div class="md-form input-group">
          <span class="input-group-addon" id="basic-addon1"><i class="fa fa-search"></i></span>
          {{search_bar_form.search_query}}
          <button style="margin:0;" class="btn btn-mdb btn-sm" type="submit">Go!</button>

        </div>
      </form>

      <div class="">

        <a href="{% url 'web_app:CreateQueryPageURL' %}" class="btn btn-secondary btn-lg btn-block"><i class="fa fa-question prefix"></i> Ask Your Query</a>

      </div>
    </div>
  </div>

  <hr>


  <!-- jumbotron banner end
-->


<!-- Side bar tags filter  -->
<div class="col-lg-3">


  <div class="widget-wrapper wow fadeIn" data-wow-delay="0.4s">
    <!--Panel-->
    <div class="card">
      <div class="card-header secondary-color white-text">
        Browse by #tags
      </div>
      <div class="card-block">
        {% for tag in tags_list %}
        <span class="chip"><a href="#"> {{tag.tagName}} </a></span>
        {% endfor %}

      </div>
    </div>
    <!--/.Panel-->
  </div>

</div>
<!-- sidebar tags filter end -->

<!--Main column-->
<div class="col-lg-6">
<h4 > {{ list_title | default:'Recent Queries' }}</h4>
  <br>
{% if query_list %}
  <!--Post-->
  {% for query in query_list %}
  <div class="post-wrapper wow fadeIn" data-wow-delay="0.3s" style="margin-bottom:15px;">
    <!--Post data-->

    <div class="card">
      <div class="card-block" style="padding-bottom:0;">
        <a href="{% url 'web_app:ShowQueryPageURL' pk=query.pk %}"><h3 style="font-size:1.5rem;" class="h3-responsive">{{query.title | safe}}</h3></a>
        <h5 class="font8">asked {% if query.service_area %} in {{query.service_area}}{% else %}Uncategorized.{% endif %} on {{query.created_date}}</h5>
        {% if query.tag1 %}<p> <span class="chip">{{query.tag1|safe}}</span>
          {% if query.tag2 %} <span class="chip" >{{query.tag2|safe}}</span> {% endif %}
          {% if query.tag3 %} <span class="chip">{{query.tag3|safe}}</span> {% endif %}
          {% if query.tag4 %} <span class="chip">{{query.tag4|safe}}</span> {% endif %}
          {% if query.tag5 %} <span class="chip">{{query.tag5|safe}}</span> {% endif %}
         </p>{% endif %}

        <br>



      </div>


      <!-- Card footer -->
      <div class="card-data">

        <!--"Read more" button-->
        <a class="link-text c-left"><h6 class="font8"><strong>1 </strong><b> answers </b> <i class="fa fa-sticky-note-o"></i></h6></a>

        <ul class="c-right">
          <li data-toggle="tooltip" data-placement="top" title="Views - Feature Under Development"><a href="#" class="font8"><i class="fa fa-eye"></i> 52</a></li>
        </ul>
      </div>
      <!-- Card footer -->


    </div>

  </div>

  {% endfor %}
  {% else %}
  <h3> Nothing to Show </h3>
  {% endif %}
  <!--/.Post-->

  <br>
  <!-- PAgination on the Page  -->
  {% if is_paginated %}

<nav>
  <ul class="pagination flex-center pg-dark  wow fadeIn">
    {% if page_obj.has_previous %}
    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}"><span aria-hidden="true">&laquo;</span>
    <span class="sr-only">Previous</span></a></li>
    {% else %}
    <li class="page-item disabled"><span><span aria-hidden="true">&laquo;</span>
    <span class="sr-only">Previous</span></span></li>
    {% endif %}
    {% for i in paginator.page_range %}
    {% if page_obj.number == i %}
    <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
    {% else %}
    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
    {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
    <li class="page-item disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
</nav>
  {% endif %}
  <!-- pagination end -->

</div>


<!--Sidebar-->
<div class="col-lg-3">


{% if user.is_authenticated %}
  <h4 >My Recent Questions</h4>
  {% if user.profile.own_queries %}
  <div class="widget-wrapper wow fadeIn" data-wow-delay="0.6s">

    <br>



    <div class="list-group">
      {% for own_query in user.profile.own_queries.all %}
      <a href="{% url 'web_app:ShowQueryPageURL' pk=own_query.pk %}" class="list-group-item">
          {{own_query.title|truncatechars:'25'}}...
      </a>
      {% endfor %}
      {% else %}
      No Questions Asked Yet.
      {% endif %}
    </div>

  </div>

{% endif %}
  {% if user.is_authenticated %}<h4 class="card-title">My Recent Answers</h4>
  <div class="widget-wrapper wow fadeIn" data-wow-delay="0.6s">
    {% if user.profile.answers_posted.all  %}

    <br>
    <div class="list-group">
        {% for answer_posted in user.profile.answers_posted.all %}
      <a href="{% url 'web_app:ShowQueryPageURL' pk=answer_posted.query.pk %}" class="list-group-item">
          {{answer_posted.text|striptags|truncatechars:'30'}}...
      </a>
      {% endfor %}

    </div>
    {% else %}
    No Questions / Queries Answered by you yet.
    {% endif %}
  </div>
  {% else %}
  <a href="{% url 'loginPageURL' %}"><h4>Login to see your recent activities</h4></a>
  {% endif %}

</div>
<!--/.Sidebar-->


</div>
{% endblock %}

web_app/templates/web_app/query-new2.html
{% extends 'web_app/base2.html' %}
{% load element_id_generator %}
{% load staticfiles %}
<!-- jumbotron banner -->
{% block main_container %}<!--Query Card-->
<div class="card">

    <!--Card content-->
    <div class="card-block">
        <!--Title-->
        <h5 class="font8">asked {% if query.service_area %} in {{query.service_area}}{% else %}Uncategorized.{% endif %} on {{query.created_date}}</h5>
        <h4 class="card-title">{{ query.title|safe}}</h4>
        <!--Text-->
        <div class="card-text">{{query.text|safe}}</div>

        {% if query.tag1 %}<p> <span class="chip">{{query.tag1|safe}}</span>
          {% if query.tag2 %} <span class="chip" >{{query.tag2|safe}}</span> {% endif %}
          {% if query.tag3 %} <span class="chip">{{query.tag3|safe}}</span> {% endif %}
          {% if query.tag4 %} <span class="chip">{{query.tag4|safe}}</span> {% endif %}
          {% if query.tag5 %} <span class="chip">{{query.tag5|safe}}</span> {% endif %}
         </p>{% endif %}

        <hr>
        <br>
        {% for discussion_thread in query.query_discussion_threads.all %}
        <p class="text-right" id="{{ discussion_thread.pk|generate_id:'query_discussion_thread' }}">{{discussion_thread.text}}</p>
        <hr>
        {% endfor %}

        <form class="" action="{% url 'web_app:CreateDiscussionThreadsQueryPageURL' querypk=query.pk %}" method="POST">
            {% csrf_token %}
          {% for field in query_discussion_form %}
          {{field}}
          {% endfor %}
          <button type="submit" name="button" class="float-right btn btn-info btn-sm">reply</button>
        </form>

    </div>
    <!--/.Card content-->

</div>
<!--/.Query CArd-->
<br>
<hr>
<br>
{% if query.answers %}
{% for answer in query.answers.all %}
<!-- Answer cards -->
<div class="card" style="margin-bottom:10px" id="{{ answer.pk|generate_id:'answer' }}">
<div class="container">
  <div class="row">
    <!-- coloumn for user meta details -->
    <div class="col-lg-2">
      <div class="container">
      <div class="row">

        <div class="col" style="margin-top:10px;">
            Posted By {{answer.created_by}}
        </div>

        </div>
        <div class="row">
          <div class="col">
            <span class="fa fa-clock-o"></span>  {{answer.created_date}}
          </div>

        </div>
        <div class="row">
          <div class="col">
            <a href="{% url 'web_app:UpdateUpvoteURL' pk=query.pk answerpk=answer.pk %}"><span class="fa fa-thumbs-o-up"></span></a>  {{answer.upvotes}}
          </div>

        </div>
        <div class="row">
          <div class="col">
            <a href="{% url 'web_app:UpdateDownvoteURL' pk=query.pk answerpk=answer.pk %}"><span class="fa fa-thumbs-o-down"></span></a>  {{answer.downvotes}}
          </div>

        </div>
      </div>
      </div>
      <!-- coloumn for user meta details end -->

      <div class="col-lg-10">
        <!--Card content-->
        <div class="card-block">
            <!--Title-->

            <!--Text-->
            {{answer.text|safe}}


        </div>
        <!--/.Card content-->
      </div>
    </div>
    {% if answer.solution_discussion_threads.all %}
    <div class="row">
      <div class="col-md-10 offset-md-2">
        <!-- the discussion threads for answers if any -->
        <hr>
        <br>
        {% for discussion_thread in answer.solution_discussion_threads.all %}
        <p class="text-right" id="{{ discussion_thread.pk|generate_id:'solution_discussion_thread' }}">{{discussion_thread.text}}</p>
        <hr>
        {% endfor %}


        <!-- the discussion threadsfor answer ends -->

      </div>

    </div>
    {% endif %}
    <form class="" action="{% url 'web_app:CreateDiscussionThreadsSolutionPageURL' querypk=query.pk answerpk=answer.pk %}" method="POST">
        {% csrf_token %}
      {% for field in solution_discussion_form %}
      {{field}}
      {% endfor %}
      <button type="submit" name="button" class="float-right btn btn-info btn-sm">reply</button>
    </form>

  </div>
</div>
{% endfor %}
{% else %}
No Answers Posted yet.
{% endif %}

<!-- Answer Cards End -->

<a href="{% url 'web_app:CreateAnswerPageURL' querypk=query.pk %}" class="btn btn-primary"> Add Answer </a>
{% endblock %}